spring:
  datasource:
    url: jdbc:mysql://localhost:3306/social_poll?createDatabaseIfNotExist=true&useSSL=false&useUnicode=true&serverTimezone=UTC
    password: root
    username: root
#  jpa:
#    hibernate:
#      ddl-auto: update

# flyway
  flyway:
    enabled: true
    locations: classpath:db/migration
    sql-migration-prefix: v
    sql-migration-separator: .




jwt:
  secret: QWERtyuyui
  expiration: 6000000
  header: Authorization
  spring: