#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/social_poll?useSSL=false&useUnicode=true&serverTimezone=UTC
#    password: root
#    username: root
#  jpa:
#    hibernate:
#      ddl-auto: update
